#!/bin/bash
echo "Все исполняемые файлы текущего каталога и их размеры:"
find -maxdepth 1 -type f -perm /111 -printf "%s %f\n"
echo "Самый большой исполняемый файл в этом каталоге:"
find -maxdepth 1 -type f -perm /111 -printf "%s %f\n" | sort -n | tail -1 | cut -d' ' -f 2
